### ISSUE TITLE
Allow heap to fire on dev environments

### ISSUE THREAD

**Issue by khuyn003** [negativetwelve/gatsby-plugin-heap#3]
**Current behavior:**
The plugin only fires the heap event when it's on a production environment.

**Expected behavior:** 
The plugin fires for all environments and gets the app id from a .env.{environment} file.

**Use case:**
To be able to test heap on dev environments w/ a sandbox heap account.

**Comment by negativetwelve** [comment]
Hi @khuyn003, great suggestion. Would you be able to submit a PR that adds a config for `enableOnDevMode` very similar to this? https://github.com/thomascarvalho/gatsby-plugin-mixpanel#configuration I'll gladly accept a PR if you have time to implement it
